add ipe-step + configuration management + openipesim

diff --git a/core/sim/rtl_sim/bin/msp430sim_c b/core/sim/rtl_sim/bin/msp430sim_c
--- a/core/sim/rtl_sim/bin/msp430sim_c
+++ b/core/sim/rtl_sim/bin/msp430sim_c
@@ -37,11 +37,14 @@
 ###############################################################################
 #                            Parameter Check                                  #
 ###############################################################################
-EXPECTED_ARGS=1
+firmware="../src/ipe/bootcode.s43" # path to firmware
+do_simulation=1
+
+EXPECTED_ARGS=2
 if [ $# -ne $EXPECTED_ARGS ]; then
   echo "ERROR    : wrong number of arguments"
-  echo "USAGE    : msp430sim_c <test name>"
-  echo "Example  : msp430sim_c sandbox"
+  echo "USAGE    : msp430sim_c <test path> <test name> <config file (optionnal) >"
+  echo "Example  : msp430sim_c ../src_c sandbox"
   echo ""
   echo "In order to switch the verilog simulator, the OMSP_SIMULATOR environment"
   echo "variable can be set to the following values:"
@@ -61,9 +64,9 @@ fi
 ###############################################################################
 #                     Check if the required files exist                       #
 ###############################################################################
-softdir=../src-c/$1;
-elffile=../src-c/$1/$1.elf;
-verfile=../src-c/$1/$1.v;
+softdir=$1;
+elffile=$1/$2.elf;
+verfile=$1/$2.v;
 incfile=../../../rtl/verilog/openMSP430_defines.v;
 submitfile=../src/submit.f;
 if [ $OMSP_SIMULATOR == "isim" ]; then
@@ -131,10 +134,12 @@ source   pmem.sh
 
 # Make C program
 echo "Compile, link & generate IHEX file (Program Memory: $pmemsize B, Data Memory: $dmemsize B, Peripheral Space: $persize B, Bootcode Memory: $bmemsize B)..."
+
+base_dir=$PWD
 cd $softdir
 make clean
 
-cp ../../bin/ipe_linker.x pmem.x
+cp $base_dir/../bin/ipe_c_linker.x pmem.x
 PMEM_BASE=$((0x10000-$pmemsize))
 STACK_INIT=$((persize+0x0080))
 BMEM_BASE=$((persize+dmemsize))
@@ -150,7 +155,7 @@ sed -ie "s/DMEM_SIZE/$dmemsize/g"         pmem.x
 sed -ie "s/PER_SIZE/$persize/g"           pmem.x
 sed -ie "s/STACK_INIT/$STACK_INIT/g"       pmem.x
 make
-cd ../../run/
+cd $base_dir/../run/
 
 # Create links
 if [[ $(uname -s) == CYGWIN* ]];
@@ -173,7 +178,7 @@ fi
 # Compile bootcode firmware
 echo "Compile, link & generate bootcode IHEX file (Bootcode Memory: $bmemsize B)"
 
-cp  "../bin/template_defs.asm"  ./pmem_defs.asm
+cp  "$base_dir/../bin/template_defs.asm"  ./pmem_defs.asm
 sed -ie "s/PMEM_SIZE/$pmemsize/g"         pmem_defs.asm
 sed -ie "s/PER_SIZE_HEX/$persize/g"       pmem_defs.asm
 sed -ie "s/BMEM_BASE_VAL/$BMEM_BASE/g" pmem_defs.asm
@@ -188,9 +193,38 @@ else
     sed -ie "s/PMEM_EDE_SIZE/$pmemsize/g" pmem_defs.asm
 fi
 
+# Checking if we need to update the firmware and if we run the test according to the config file
+config_file=$softdir/${3-config.json};
+
+echo $config_file
+
+if [ ! -e $config_file ]; then
+    echo "Configuration file doesn't exist: $config_file"
+else
+    echo "Configuration file $config_file found!"
+    
+    echo "\$ cat $config_file | python3 -c \"import sys, json; print(json.load(sys.stdin)['firmware'])\""
+    RESULT="$(cat $config_file | python3 -c "import sys, json; print(json.load(sys.stdin)['firmware'])")"
+    if [ $? -ne 0 ]; then
+        echo "Failed to retrieve firmware in config file. Using $firmware"
+    else
+        firmware=../src/ipe/$RESULT.s43
+        echo "Firmware $firmware  will be used"
+    fi
+
+    echo "\$ cat $config_file | python3 -c \"import sys, json; print(json.load(sys.stdin)['simulation'])\""
+    RESULT="$(cat $config_file | python3 -c "import sys, json; print(json.load(sys.stdin)['simulation'])")"
+    if [ $? -ne 0 ]; then
+        echo "Failed to retrieve simulation parameter in config file. Going to perform the simulation"
+    else
+        do_simulation=$RESULT
+        echo "Doing simulation: $do_simulation"
+    fi
+fi
+
 echo ""
-echo "\$ $MSPGCC_PFX-as      -alsm ../src/ipe/bootcode.s43 -o bootcode.o > bmem.l43"
-$MSPGCC_PFX-as      -alsm ../src/ipe/bootcode.s43 -o bootcode.o    > bmem.l43
+echo "\$ $MSPGCC_PFX-as      -alsm $firmware -o bootcode.o > bmem.l43"
+$MSPGCC_PFX-as      -alsm $firmware -o bootcode.o    > bmem.l43
 echo "\$ $MSPGCC_PFX-ld      -L$softdir -T $softdir/pmem.x bootcode.o -o bmem.elf"
 $MSPGCC_PFX-ld      -L$softdir -T $softdir/pmem.x   bootcode.o    -o bmem.elf
 echo "\$ $MSPGCC_PFX-objcopy -O ihex bmem.elf bmem.ihex"
@@ -203,6 +237,8 @@ echo "Convert IHEX file to Verilog MEMH format... (pmem size: $pmemsize, bmem si
 ../bin/ihex2mem.tcl -ihex pmem.ihex -out pmem.mem -mem_size $pmemsize
 ../bin/ihex2mem.tcl -ihex bmem.ihex -out bmem.mem -mem_size $bmemsize -mem_offset $bmem_offset
 
-# Start verilog simulation
-echo "Start Verilog simulation..."
-../bin/rtlsim.sh    stimulus.v pmem.mem $submitfile 0 "NO_DMA_VERIF"
+if [ $do_simulation -ne 0 ]; then
+    # Start verilog simulation
+    echo "Start Verilog simulation..."
+    ../bin/rtlsim.sh    stimulus.v pmem.mem $submitfile 0 "NO_DMA_VERIF"
+fi 
